export const ALL_MOVIES_LOADED_REQUEST = "ALL_MOVIES_LOADED_REQUEST";
export const ALL_MOVIES_LOADED_SUCCESS = "ALL_MOVIES_LOADED_SUCCESS";
export const ALL_MOVIES_LOADED_FAILURE = "ALL_MOVIES_LOADED_FAILURE";

export const SINGLE_MOVIE_LOADED_REQUEST = "SINGLE_MOVIE_LOADED_REQUEST";
export const SINGLE_MOVIE_LOADED_SUCCESS = "SINGLE_MOVIE_LOADED_SUCCESS";
export const SINGLE_MOVIE_LOADED_FAILURE = "SINGLE_MOVIE_LOADED_FAILURE";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
